Escuela:
  Nombre: "Instituto Ballonti"
Clase:
  Nombre: "Aula Estable"
  Encargos:
    Archivo: "pedidos.json"
    Encendido: true
    Productos:
      - Nombre: Tortilla de patata
        Precio: 8
      - Nombre: Bizcocho
        Precio: 8
Comedor:
  Encendido: true
  Url: "https://raw.githubusercontent.com/SistemaAxel/Comedores/main/comedores"
  Nombre: "Kanpazar"
  Id: "00001"
  Menus:
    - Basal
    - NoLegumbres